---
title: "Reshape Data by Category"
subtitle: "Fundamentals of Data Science"
author: "[First name][Last initial]"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Syllabus Reminders

* You must submit your mini-assignment individually by end-of-class or end-of-day. Your name must exist in your mini-assignment and the names of your collaborators.
* Mini-assignments are marked mostly on completion, and partially on correctness. It will be marked either pass or fail, there will no detailed feedback on mini-assignments, and no opportunities for revisions and make-up.

# Instructions

* For the exercises, please provide your answers in full sentences.
* Write your answers by replacing the text "[Write your answer here]".
* Please read the problems fully and carefully before answering.
* When finished, knit this `.Rmd` to `.html`.
* Submit this `.Rmd` and the recently knitted `.html`.

# Collaborators

::: {style="color: blue;"}
[Write your answer here]
:::

# Exercises

## Problem 1

Create a code chunk. In this chunk, load the `palmerpenguins` and the `tidyverse` packages.  These packages are pre-installed.

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 2

Examine the `penguins` tibble. You may notice that there are `NA` values, which means missing data. Use the `drop_na()` function to remove all rows that has missing values on any column. Here, you may use chaining to pipe the tibble into `drop_na()`, and save the new tibble as a new R variable. How many rows was removed in the data set?

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 3

Use the `group()` and `summarise()` verbs to count --using the `n()` function-- how many penguins in each island in the `island` column for each species in the `species` column. Store this summarised tibble into a new R variable.

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 4

Use the `pivot_wider()` verb to reshape the resulting tibble in Problem 3 to reshape the tibble where the columns are the categories of the `island` variable. Store this reshaped tibble into a new R variable.

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 5

Use the `pivot_longer()` verb to reshape the resulting tibble in Problem 4 back to its original form in Problem 3.

::: {style="color: blue;"}
[Write your answer here]
:::
