---
title: "Modify a RMarkdown Document"
subtitle: "Fundamentals of Data Science"
author: "[First name][Last initial]"
date: "`r Sys.Date()`"
output: html_document
---

# Syllabus Reminders

* You must submit your mini-assignment individually by end-of-class or end-of-day. Your name must exist in your mini-assignment and the names of your collaborators.
* Mini-assignments are marked mostly on completion, and partially on correctness. It will be marked either pass or fail, there will no detailed feedback on mini-assignments, and no opportunities for revisions and make-up.

# Instructions

* For the exercises, please provide your answers in full sentences.
* Write your answers by replacing the text "[Write your answer here]".
* Please read the problems fully and carefully before answering.
* When finished, knit this `.Rmd` to `.html`.
* Submit this `.Rmd` and the recently knitted `.html`.

# Collaborators

::: {style="color: blue;"}
[Write your answer here]
:::

# Exercises

## Problem 1

Describe the five basic parts of an RMarkdown document. What are they? What are their functions?

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 2

Explain the similarities between running R commands on the console versus running R commands in the RMarkdown code chunks.

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 3

When "knitting" an RMarkdown document, describe what happens in general. What does it create?

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 4

The R code chunks in an RMarkdown document runs in two ways. Describe the difference on what happens to the R commands when "knitting" vs running the code blocks in the RMarkdown file.

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 5

Describe the levels of headers according to the "#" key.

::: {style="color: blue;"}
[Write your answer here]
:::

## Problem 6

On the upper left hand corner of this pane, there are two buttons "Source" and "Visual". Describe your observations when clicking the button "Visual". What are the differences and similarities between the two settings?

::: {style="color: blue;"}
[Write your answer here]
:::
